apiVersion: v1
entries:
  cms:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-31T11:31:25.627939+02:00"
    description: A Helm chart for Kubernetes
    digest: dcebf4d876156ffaba97cb86bf0f781fec0540b07d5c7110019b800333d11783
    name: cms
    type: application
    urls:
    - https://opera-groupe.github.io/opera-groupe-helm/charts/cms-0.1.0.tgz
    version: 0.1.0
  frontend-tenant-appointment-booker:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-31T11:31:25.628859+02:00"
    description: A Helm chart for Kubernetes
    digest: f0fc6cd1c66a78430a057c2a75d7b790b5990c099c0963d6db81878b32173556
    name: frontend-tenant-appointment-booker
    type: application
    urls:
    - https://opera-groupe.github.io/opera-groupe-helm/charts/frontend-tenant-appointment-booker-0.1.0.tgz
    version: 0.1.0
generated: "2023-03-31T11:31:25.626721+02:00"
