apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cms.fullname" . }}
  labels:
    {{- include "cms.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cms.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cms.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 1337
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: ADMIN_JWT_SECRET
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: API_TOKEN_SALT
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: APP_KEYS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: JWT_SECRET
            - name: OG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: OG_API_KEY
            - name: OG_API_URL
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: OG_API_URL
            - name: SMS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: SMS_API_KEY
            - name: SMS_API_URL
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: SMS_API_URL
            - name: SMTP_DEFAULT_FROM
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: SMTP_DEFAULT_FROM
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: SMTP_HOST
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: SMTP_PASSWORD
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: SMTP_PORT
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: SMTP_USER
            - name: EMAIL_CC
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: EMAIL_CC
            - name: TENANT_APPOINTMENT_BOOKER_URL
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: TENANT_APPOINTMENT_BOOKER_URL
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DATABASE_HOST
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DATABASE_NAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DATABASE_PASSWORD
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DATABASE_PORT
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DATABASE_USER
            - name: TZ
              value: {{ .Values.timeZone }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
