apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-contractor-extranet.fullname" . }}
  labels:
    {{- include "frontend-contractor-extranet.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "frontend-contractor-extranet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "frontend-contractor-extranet.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "frontend-contractor-extranet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api
              port: 3000
          readinessProbe:
            httpGet:
              path: /api
              port: 3000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NEXT_PUBLIC_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: contractor-extranet-env
                  key: NEXT_PUBLIC_SERVER_URL
            - name: SERVER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: contractor-extranet-env
                  key: SERVER_BASE_URL
            - name: NEXT_PUBLIC_OG_EXTRANET_URL
              valueFrom:
                secretKeyRef:
                  name: contractor-extranet-env
                  key: NEXT_PUBLIC_OG_EXTRANET_URL
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
