name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name 'github-actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          packages_with_index: true
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
